#!/usr/bin/env node
/**
 * Bundle three.js from npm into the single self-contained module the page imports.
 *
 * WHY THIS EXISTS
 * `js/pixel-avatar.js` needs a browser-loadable ES module, so what we ship has to be a
 * plain file at a plain path — a bare `import "three"` cannot resolve in a browser
 * without an import map or a bundler. The previous arrangement checked a 672 KB minified
 * build into git instead, and that had two real costs: nothing in the repo recorded which
 * revision it was (it sat at r169 while upstream moved on), and no tool could tell you it
 * had gone stale.
 *
 * WHY BUNDLE RATHER THAN COPY
 * Copying used to work, but three.js stopped publishing minified builds at r170 and split
 * `three.module.js` away from `three.core.js`, so a copy would now be two files totalling
 * ~2.1 MB. Bundling yields one ~665 KB self-contained file — the same size as the blob it
 * replaces — while keeping the revision in `package.json` and the lockfile, where
 * `npm update` and Dependabot can see it.
 *
 * `three` is pinned to an exact version on purpose: revisions routinely rename or drop
 * APIs, and this card reaches for two dozen of them. Upgrading is meant to be a
 * deliberate, tested step rather than something a `^` range does behind your back. The
 * export assertion below is what makes that upgrade safe — it fails the build if a
 * revision removes anything the card actually calls.
 *
 * Output (git-ignored; regenerated by CI before every deploy):
 *   js/vendor/three.module.min.js
 */

import { build } from "esbuild";
import { mkdir, readFile, rm } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "js", "vendor");
const OUT_FILE = join(OUT_DIR, "three.module.min.js");
const CONSUMER = join(ROOT, "js", "pixel-avatar.js");
const THREE_PKG = join(ROOT, "node_modules", "three", "package.json");

/**
 * The installed three revision, from the package itself rather than from the bundle:
 * esbuild renames the `REVISION` binding and re-exports it as an alias, so the literal
 * is no longer adjacent to the name in the output.
 */
async function installedRevision() {
  const pkg = JSON.parse(await readFile(THREE_PKG, "utf8"));
  return pkg.version;
}

/** The `THREE.X` names the bundle must expose, read from the file that consumes them. */
async function requiredExports() {
  const source = await readFile(CONSUMER, "utf8");
  const names = new Set(
    [...source.matchAll(/\bTHREE\.([A-Za-z_$][\w$]*)/g)].map((m) => m[1]),
  );
  if (names.size === 0) {
    throw new Error(
      `No THREE.* usages found in ${CONSUMER} — is the consumer still the 3D card?`,
    );
  }
  return names;
}

/**
 * esbuild's ESM output ends with one or more `export{a as Foo,b as Bar}` clauses. Reading
 * the real export list beats grepping for identifiers, which would also match a mangled
 * local that happens to share a name.
 */
function exportedNames(code) {
  const names = new Set();
  for (const match of code.matchAll(/export\s*\{([^}]*)\}/g)) {
    for (const clause of match[1].split(",")) {
      const parts = clause.split(/\s+as\s+/);
      const name = parts[parts.length - 1].trim();
      if (name) names.add(name);
    }
  }
  return names;
}

async function main() {
  const required = await requiredExports();

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  await build({
    stdin: {
      contents: "export * from 'three';",
      resolveDir: ROOT,
      sourcefile: "three-entry.js",
      loader: "js",
    },
    bundle: true,
    minify: true,
    format: "esm",
    target: "es2020",
    outfile: OUT_FILE,
    // three.js is MIT and its banner must survive minification.
    legalComments: "inline",
  });

  const code = await readFile(OUT_FILE, "utf8");

  if (/^\s*import[\s{]/m.test(code) || /\bfrom\s*["'][./]/.test(code)) {
    throw new Error(
      "Bundle still contains an import — it would 404 in the browser at that path.",
    );
  }

  const exported = exportedNames(code);
  const missing = [...required].filter((name) => !exported.has(name)).sort();
  if (missing.length > 0) {
    throw new Error(
      `three.js no longer exports: ${missing.join(", ")}.\n` +
        `${CONSUMER} calls these, so the upgrade is not a drop-in — fix the call sites ` +
        "or pin back to the previous revision.",
    );
  }

  const kb = (Buffer.byteLength(code) / 1024).toFixed(0);
  const version = await installedRevision();
  console.log(
    `three: v${version}, ${exported.size} exports, ${required.size} verified, ` +
      `${kb} KB -> js/vendor/`,
  );
}

main().catch((error) => {
  console.error(`build-vendor failed: ${error.message}`);
  process.exit(1);
});
