#!/usr/bin/env node
/**
 * Generate the self-hosted webfont payload served from `/fonts`.
 *
 * WHY BUILD-TIME SELF-HOSTING
 * This site is read from mainland China, where `fonts.googleapis.com` is unreliable.
 * Next.js solves that with `next/font` (fetch at build time, serve from your own
 * origin). This repo is a plain static site with no bundler, so this script is the
 * equivalent: slices come from npm at build time, are served from our own origin at
 * runtime, and no font binary is committed to git.
 *
 * WHY WE COPY INSTEAD OF SUBSETTING OURSELVES
 * CJK only stays practical when a font is split into ~100 `unicode-range` slices, so
 * that a browser downloads just the slices the current page actually renders. The
 * `@fontsource-variable/*` packages already publish exactly that split, generated
 * upstream from the SIL OFL 1.1 sources. Re-slicing here would add a failure mode
 * without adding anything, so we copy the slices verbatim and only concatenate their
 * CSS into one stylesheet whose URLs resolve from `/fonts/fonts.css`.
 *
 * Output (git-ignored; regenerated by CI before every deploy):
 *   fonts/fonts.css       one concatenated @font-face list
 *   fonts/files/*.woff2   only the slices those rules reference
 */

import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "fonts");
const OUT_FILES = join(OUT_DIR, "files");

/**
 * One entry per `@fontsource-variable` package, listing the stylesheets to take.
 *
 * Only the `wght` axes are used. No italic face is shipped, because the site renders no
 * italic text at all — the single rule that declared `font-style: italic` targeted a
 * class absent from the markup, and there is no `<em>`/`<i>` anywhere. Shipping one
 * would put ~230 KB of never-requested files into the deployed payload. If italic text
 * is ever introduced, add `wght-italic.css` here; CJK would still be synthesised as an
 * oblique, since Source Han Sans has no true italic.
 */
const SOURCES = [
  { pkg: "@fontsource-variable/inter", css: ["wght.css"] },
  { pkg: "@fontsource-variable/jetbrains-mono", css: ["wght.css"] },
  { pkg: "@fontsource-variable/noto-sans-sc", css: ["wght.css"] },
];

/** Preloaded in `index.html`; asserted below so a rename fails the build loudly. */
const PRELOADED = "inter-latin-wght-normal.woff2";

/**
 * `@fontsource` emits the deprecated `format('woff2-variations')`. A browser that no
 * longer recognises that string skips the source entirely — no font at all — whereas
 * a plain `woff2` hint is accepted everywhere and still carries the variation axes.
 * So we normalise it rather than trusting the legacy keyword.
 */
function normaliseFormat(css) {
  return css.replaceAll(
    "format('woff2-variations')",
    "format('woff2')",
  );
}

async function collect({ pkg, css: sheets }) {
  const pkgDir = join(ROOT, "node_modules", pkg);
  if (!existsSync(pkgDir)) {
    throw new Error(
      `${pkg} is not installed. Run \`npm install --ignore-scripts\` first.`,
    );
  }

  const chunks = [];
  const files = new Set();

  for (const sheet of sheets) {
    const sheetPath = join(pkgDir, sheet);
    if (!existsSync(sheetPath)) {
      throw new Error(`${pkg} does not ship ${sheet} (looked in ${sheetPath}).`);
    }

    const raw = await readFile(sheetPath, "utf8");
    const urls = [...raw.matchAll(/url\(\.\/files\/([^)]+)\)/g)].map((m) => m[1]);
    if (urls.length === 0) {
      throw new Error(`${pkg}/${sheet} referenced no slices — check the package layout.`);
    }

    for (const name of urls) {
      const src = join(pkgDir, "files", name);
      if (!existsSync(src)) {
        throw new Error(`${pkg}/${sheet} references a missing slice: ${name}`);
      }
      files.add(name);
    }

    chunks.push(`/* ---- ${pkg}/${sheet} ---- */\n${normaliseFormat(raw).trim()}`);
  }

  return { chunks, files };
}

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_FILES, { recursive: true });

  const chunks = [];
  const allFiles = new Set();

  for (const source of SOURCES) {
    const { chunks: c, files } = await collect(source);
    chunks.push(...c);
    for (const f of files) allFiles.add(f);
  }

  for (const name of allFiles) {
    const owner = SOURCES.find((s) =>
      existsSync(join(ROOT, "node_modules", s.pkg, "files", name)),
    );
    await copyFile(
      join(ROOT, "node_modules", owner.pkg, "files", name),
      join(OUT_FILES, name),
    );
  }

  const header = [
    "/* GENERATED by scripts/build-fonts.mjs — do not edit, do not commit. */",
    `/* ${allFiles.size} slices from ${SOURCES.length} packages. */`,
    "",
  ].join("\n");

  await writeFile(join(OUT_DIR, "fonts.css"), header + chunks.join("\n\n") + "\n");

  if (!allFiles.has(PRELOADED)) {
    throw new Error(
      `index.html preloads ${PRELOADED}, but the build did not produce it. ` +
        "Update the preload href (or this constant) to match the package contents.",
    );
  }

  const rules = chunks.join("\n").match(/@font-face/g)?.length ?? 0;
  console.log(
    `fonts: ${rules} @font-face rules, ${allFiles.size} woff2 slices -> fonts/`,
  );
}

main().catch((error) => {
  console.error(`build-fonts failed: ${error.message}`);
  process.exit(1);
});
